[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
pretty = True
explicit_package_bases = True

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-coc.*]
ignore_missing_imports = True

[mypy-groq.*]
ignore_missing_imports = True